name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
        shell: bash

  goodbye_job:
    runs-on: ubuntu-latest
    needs: hello_world_job

    steps:
      - name: Print Goodbye
        run: echo "Goodbye, World!"
        shell: bash