name: Create a comment on newly raised issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: create comment with api
        run: |
          gh api -X POST \
            /repos/${ORGANIZATION}/${REPOSITORY}/issues/${{ github.event.issue.number }}/comments \
            -f body='This is a comment created with the GitHub CLI'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
