name: Greet users on push to main branch

on:
  push:
    branches: [main]

jobs:
  greet-users:
    runs-on: ubuntu-latest
    steps:
      - name: Greet users
        run: echo "Hello, users! A new commit has been pushed to the main branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}